DROP TABLE IF EXISTS employee;

CREATE TABLE employee
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR(255) NOT NULL,
    email           VARCHAR(255) NOT NULL UNIQUE,
    ph_no           VARCHAR(50)  NOT NULL,
    address         VARCHAR(255) NOT NULL,
    date_of_birth   DATE         NOT NULL,
    registered_date DATE         NOT NULL,
    password        VARCHAR(255) NOT NULL,
    profile_pic     VARCHAR(512)
);


INSERT INTO employee (name, email, ph_no, address, date_of_birth, registered_date, password, profile_pic)
VALUES ('Admin Akash', 'admin@abc.com', '1234567890', 'Kolkata, West Bengal', DATE '1995-01-01', DATE '2012-01-01',
        'Pass@123', 'http://images/example.png');

INSERT INTO employee
(name, email, ph_no, address, date_of_birth, registered_date, password, profile_pic)
VALUES
-- 1–10
('Rahul Das', 'rahul.das1@example.com', '9000000001', 'Kolkata, West Bengal', '1990-01-10', '2012-03-15', 'Pass@123',
 NULL),
('Sneha Iyer', 'sneha.iyer2@example.com', '9000000002', 'Chennai, Tamil Nadu', '1992-05-20', '2015-06-21', 'Pass@123',
 NULL),
('Kunal Shah', 'kunal.shah3@example.com', '9000000003', 'Mumbai, Maharashtra', '1991-07-11', '2011-08-09', 'Pass@123',
 NULL),
('Pooja Mehta', 'pooja.mehta4@example.com', '9000000004', 'Ahmedabad, Gujarat', '1993-09-25', '2018-11-30', 'Pass@123',
 NULL),
('Amit Singh', 'amit.singh5@example.com', '9000000005', 'Lucknow, UP', '1989-02-14', '2010-01-12', 'Pass@123', NULL),
('Ritika Kapoor', 'ritika.kapoor6@example.com', '9000000006', 'Delhi', '1994-04-18', '2020-07-19', 'Pass@123', NULL),
('Nikhil Verma', 'nikhil.verma7@example.com', '9000000007', 'Bhopal, MP', '1992-06-30', '2017-03-22', 'Pass@123', NULL),
('Ankit Jain', 'ankit.jain8@example.com', '9000000008', 'Jaipur, Rajasthan', '1995-12-01', '2022-02-10', 'Pass@123',
 NULL),
('Meera Nair', 'meera.nair9@example.com', '9000000009', 'Kochi, Kerala', '1993-03-03', '2014-09-14', 'Pass@123', NULL),
('Varun Reddy', 'varun.reddy10@example.com', '9000000010', 'Hyderabad, Telangana', '1990-10-10', '2016-05-05',
 'Pass@123', NULL),

-- 11–20
('Divya Sharma', 'divya.sharma11@example.com', '9000000011', 'Delhi', '1996-08-08', '2023-01-01', 'Pass@123', NULL),
('Rohit Kulkarni', 'rohit.kulkarni12@example.com', '9000000012', 'Pune, Maharashtra', '1991-11-11', '2013-12-12',
 'Pass@123', NULL),
('Neeraj Yadav', 'neeraj.yadav13@example.com', '9000000013', 'Patna, Bihar', '1992-02-22', '2019-04-04', 'Pass@123',
 NULL),
('Shreya Gupta', 'shreya.gupta14@example.com', '9000000014', 'Kanpur, UP', '1997-06-15', '2024-06-10', 'Pass@123',
 NULL),
('Tarun Malhotra', 'tarun.malhotra15@example.com', '9000000015', 'Delhi', '1993-07-07', '2011-10-10', 'Pass@123', NULL),
('Alok Mishra', 'alok.mishra16@example.com', '9000000016', 'Varanasi, UP', '1988-01-01', '2010-05-20', 'Pass@123',
 NULL),
('Rashmi Patil', 'rashmi.patil17@example.com', '9000000017', 'Nagpur, Maharashtra', '1994-04-04', '2018-08-08',
 'Pass@123', NULL),
('Deepak Choudhary', 'deepak.choudhary18@example.com', '9000000018', 'Jaipur, Rajasthan', '1990-09-09', '2016-02-14',
 'Pass@123', NULL),
('Komal Bansal', 'komal.bansal19@example.com', '9000000019', 'Delhi', '1995-05-05', '2021-03-03', 'Pass@123', NULL),
('Suresh Pillai', 'suresh.pillai20@example.com', '9000000020', 'Thiruvananthapuram, Kerala', '1989-12-12', '2012-07-07',
 'Pass@123', NULL),

-- 21–30
('Manoj Kumar', 'manoj.kumar21@example.com', '9000000021', 'Ranchi, Jharkhand', '1991-03-15', '2015-09-09', 'Pass@123',
 NULL),
('Asha Menon', 'asha.menon22@example.com', '9000000022', 'Kochi, Kerala', '1996-07-17', '2022-12-01', 'Pass@123', NULL),
('Kiran Shetty', 'kiran.shetty23@example.com', '9000000023', 'Mangalore, Karnataka', '1993-08-19', '2014-11-11',
 'Pass@123', NULL),
('Ravi Teja', 'ravi.teja24@example.com', '9000000024', 'Vijayawada, AP', '1992-09-21', '2017-01-25', 'Pass@123', NULL),
('Bhavna Soni', 'bhavna.soni25@example.com', '9000000025', 'Surat, Gujarat', '1994-02-14', '2013-06-06', 'Pass@123',
 NULL),
('Gaurav Arora', 'gaurav.arora26@example.com', '9000000026', 'Chandigarh', '1990-11-11', '2011-04-04', 'Pass@123',
 NULL),
('Tina Dutta', 'tina.dutta27@example.com', '9000000027', 'Kolkata, West Bengal', '1997-03-30', '2025-05-05', 'Pass@123',
 NULL),
('Harish Naidu', 'harish.naidu28@example.com', '9000000028', 'Visakhapatnam, AP', '1991-06-06', '2018-09-09',
 'Pass@123', NULL),
('Lavanya Iyer', 'lavanya.iyer29@example.com', '9000000029', 'Chennai, Tamil Nadu', '1995-10-10', '2020-10-10',
 'Pass@123', NULL),
('Sameer Khan', 'sameer.khan30@example.com', '9000000030', 'Bhopal, MP', '1993-12-12', '2016-06-06', 'Pass@123', NULL),

-- 31–40
('Imran Ali', 'imran.ali31@example.com', '9000000031', 'Hyderabad, Telangana', '1990-01-01', '2012-02-02', 'Pass@123',
 NULL),
('Preeti Joshi', 'preeti.joshi32@example.com', '9000000032', 'Indore, MP', '1996-05-05', '2023-03-03', 'Pass@123',
 NULL),
('Vivek Pandey', 'vivek.pandey33@example.com', '9000000033', 'Allahabad, UP', '1992-07-07', '2015-05-05', 'Pass@123',
 NULL),
('Swati Kulshrestha', 'swati.kul34@example.com', '9000000034', 'Gwalior, MP', '1994-09-09', '2019-09-09', 'Pass@123',
 NULL),
('Rajeev Saxena', 'rajeev.saxena35@example.com', '9000000035', 'Noida, UP', '1989-03-03', '2011-11-11', 'Pass@123',
 NULL),
('Neha Bhat', 'neha.bhat36@example.com', '9000000036', 'Srinagar, J&K', '1995-08-08', '2022-02-02', 'Pass@123', NULL),
('Sanjay Rao', 'sanjay.rao37@example.com', '9000000037', 'Bangalore, Karnataka', '1991-01-21', '2014-04-14', 'Pass@123',
 NULL),
('Pallavi Desai', 'pallavi.desai38@example.com', '9000000038', 'Surat, Gujarat', '1993-11-30', '2017-07-07', 'Pass@123',
 NULL),
('Arvind Menon', 'arvind.menon39@example.com', '9000000039', 'Kochi, Kerala', '1990-02-02', '2013-03-03', 'Pass@123',
 NULL),
('Tejas Patel', 'tejas.patel40@example.com', '9000000040', 'Ahmedabad, Gujarat', '1994-04-14', '2018-08-18', 'Pass@123',
 NULL),

-- 41–52
('Yash Thakur', 'yash.thakur41@example.com', '9000000041', 'Shimla, HP', '1997-07-07', '2024-04-04', 'Pass@123', NULL),
('Anjali Roy', 'anjali.roy42@example.com', '9000000042', 'Kolkata, WB', '1996-06-06', '2023-06-06', 'Pass@123', NULL),
('Mohit Saini', 'mohit.saini43@example.com', '9000000043', 'Rohtak, Haryana', '1992-12-12', '2015-12-12', 'Pass@123',
 NULL),
('Renu Bala', 'renu.bala44@example.com', '9000000044', 'Amritsar, Punjab', '1995-01-15', '2021-01-01', 'Pass@123',
 NULL),
('Karthik R', 'karthik.r45@example.com', '9000000045', 'Chennai, Tamil Nadu', '1993-03-03', '2016-03-03', 'Pass@123',
 NULL),
('Sathish Kumar', 'sathish.kumar46@example.com', '9000000046', 'Coimbatore, Tamil Nadu', '1991-04-04', '2012-12-12',
 'Pass@123', NULL),
('Deepa Krishnan', 'deepa.krishnan47@example.com', '9000000047', 'Madurai, Tamil Nadu', '1994-05-05', '2019-05-05',
 'Pass@123', NULL),
('Lokesh Gowda', 'lokesh.gowda48@example.com', '9000000048', 'Mysore, Karnataka', '1992-06-06', '2017-07-07',
 'Pass@123', NULL),
('Ajay Rawat', 'ajay.rawat49@example.com', '9000000049', 'Dehradun, Uttarakhand', '1990-07-07', '2013-08-08',
 'Pass@123', NULL),
('Naveen Pillai', 'naveen.pillai50@example.com', '9000000050', 'Kollam, Kerala', '1993-08-08', '2018-09-09', 'Pass@123',
 NULL),
('Rakesh Jha', 'rakesh.jha51@example.com', '9000000051', 'Darbhanga, Bihar', '1991-09-09', '2014-10-10', 'Pass@123',
 NULL),
('Sunita Devi', 'sunita.devi52@example.com', '9000000052', 'Gaya, Bihar', '1995-10-10', '2020-11-11', 'Pass@123', NULL);



UPDATE employee
SET profile_pic = 'http://localhost:4000/uploads/1774417318457-MPHASIS-logo.png';